### Login
POST http://localhost:3000/api/v1/auth/login 
Content-Type: application/json
{
    "username": "juan",
    "password": "5678910"
}

### Entering secret area with valid token
POST http://localhost:3000/secret-area
Content-Type: application/json
Authorization: INVALID-TOKEN

### Refresh tokens with a valid refresh token
PUT http://localhost:3000/api/v1/auth/refresh-tokens
Authorization: 2212799a-6e50-4d9e-82ee-8421ed26a958







### Log out with a valid token
DELETE http://localhost:3000/api/v1/auth/logout
Authorization: 309d21b0-8cd0-47d1-960a-f6b67915d375
