POST http://localhost:3000/api/v1/auth/login 
Content-Type: application/json
Authorization: 3720d58d-3658-479c-abf3-61529c67db8e

{
    "username": "jose",
    "password": "123456"
}

### 
POST http://localhost:3000/secret-area
Content-Type: application/json
Authorization: 57bd71a4-e153-449a-a784-ee184c610842

