#Login
POST http://localhost:3000/api/v1/auth/login 
Content-Type: application/x-www-form-urlencoded

client_id=juan
&client_secret=5678910


### Entering secret area with valid token
POST http://localhost:3000/secret-area
Content-Type: application/json
Authorization: 32523292-6c97-434f-821f-1845e82d1a9a

### Refresh tokens with a valid refresh token
POST http://localhost:3000/api/v1/auth/refresh-tokens
Content-Type: application/x-www-form-urlencoded

refresh_token=1e6b26a4-8f90-4850-bd02-fa26150c8d28

### Log out with a valid token
DELETE http://localhost:3000/api/v1/auth/logout
Authorization: 32523292-6c97-434f-821f-1845e82d1a9a


### Entering secret area with valid token
POST http://localhost:3000/test
Content-Type: application/json

{
  "internalCode": "internal code",
  "description": "description",
  "quantity": 1,
  "pricePerUnit": 2,
  "unit": "unities",
  "purchaseTime": 5,
  "internalNotes": "internal nodes"
}